// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat-gateway.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type Message struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*Message_Login_
	//	*Message_Logout_
	//	*Message_Message_
	//	*Message_Shutdown_
	Event                isMessage_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isMessage_Event interface {
	isMessage_Event()
}

type Message_Login_ struct {
	Login *Message_Login `protobuf:"bytes,2,opt,name=login,proto3,oneof"`
}

type Message_Logout_ struct {
	Logout *Message_Logout `protobuf:"bytes,3,opt,name=logout,proto3,oneof"`
}

type Message_Message_ struct {
	Message *Message_Message `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type Message_Shutdown_ struct {
	Shutdown *Message_Shutdown `protobuf:"bytes,5,opt,name=shutdown,proto3,oneof"`
}

func (*Message_Login_) isMessage_Event() {}

func (*Message_Logout_) isMessage_Event() {}

func (*Message_Message_) isMessage_Event() {}

func (*Message_Shutdown_) isMessage_Event() {}

func (m *Message) GetEvent() isMessage_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Message) GetLogin() *Message_Login {
	if x, ok := m.GetEvent().(*Message_Login_); ok {
		return x.Login
	}
	return nil
}

func (m *Message) GetLogout() *Message_Logout {
	if x, ok := m.GetEvent().(*Message_Logout_); ok {
		return x.Logout
	}
	return nil
}

func (m *Message) GetMessage() *Message_Message {
	if x, ok := m.GetEvent().(*Message_Message_); ok {
		return x.Message
	}
	return nil
}

func (m *Message) GetShutdown() *Message_Shutdown {
	if x, ok := m.GetEvent().(*Message_Shutdown_); ok {
		return x.Shutdown
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Login_)(nil),
		(*Message_Logout_)(nil),
		(*Message_Message_)(nil),
		(*Message_Shutdown_)(nil),
	}
}

type Message_Login struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Login) Reset()         { *m = Message_Login{} }
func (m *Message_Login) String() string { return proto.CompactTextString(m) }
func (*Message_Login) ProtoMessage()    {}
func (*Message_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{4, 0}
}

func (m *Message_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Login.Unmarshal(m, b)
}
func (m *Message_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Login.Marshal(b, m, deterministic)
}
func (m *Message_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Login.Merge(m, src)
}
func (m *Message_Login) XXX_Size() int {
	return xxx_messageInfo_Message_Login.Size(m)
}
func (m *Message_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Login proto.InternalMessageInfo

func (m *Message_Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Message_Logout struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Logout) Reset()         { *m = Message_Logout{} }
func (m *Message_Logout) String() string { return proto.CompactTextString(m) }
func (*Message_Logout) ProtoMessage()    {}
func (*Message_Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{4, 1}
}

func (m *Message_Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Logout.Unmarshal(m, b)
}
func (m *Message_Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Logout.Marshal(b, m, deterministic)
}
func (m *Message_Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Logout.Merge(m, src)
}
func (m *Message_Logout) XXX_Size() int {
	return xxx_messageInfo_Message_Logout.Size(m)
}
func (m *Message_Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Logout proto.InternalMessageInfo

func (m *Message_Logout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Message_Message struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Message) Reset()         { *m = Message_Message{} }
func (m *Message_Message) String() string { return proto.CompactTextString(m) }
func (*Message_Message) ProtoMessage()    {}
func (*Message_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{4, 2}
}

func (m *Message_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Message.Unmarshal(m, b)
}
func (m *Message_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Message.Marshal(b, m, deterministic)
}
func (m *Message_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Message.Merge(m, src)
}
func (m *Message_Message) XXX_Size() int {
	return xxx_messageInfo_Message_Message.Size(m)
}
func (m *Message_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Message proto.InternalMessageInfo

func (m *Message_Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message_Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Message_Shutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Shutdown) Reset()         { *m = Message_Shutdown{} }
func (m *Message_Shutdown) String() string { return proto.CompactTextString(m) }
func (*Message_Shutdown) ProtoMessage()    {}
func (*Message_Shutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b278c71b6605e99, []int{4, 3}
}

func (m *Message_Shutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Shutdown.Unmarshal(m, b)
}
func (m *Message_Shutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Shutdown.Marshal(b, m, deterministic)
}
func (m *Message_Shutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Shutdown.Merge(m, src)
}
func (m *Message_Shutdown) XXX_Size() int {
	return xxx_messageInfo_Message_Shutdown.Size(m)
}
func (m *Message_Shutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Shutdown.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Shutdown proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "protocol.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protocol.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "protocol.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "protocol.LogoutResponse")
	proto.RegisterType((*Message)(nil), "protocol.Message")
	proto.RegisterType((*Message_Login)(nil), "protocol.Message.Login")
	proto.RegisterType((*Message_Logout)(nil), "protocol.Message.Logout")
	proto.RegisterType((*Message_Message)(nil), "protocol.Message.Message")
	proto.RegisterType((*Message_Shutdown)(nil), "protocol.Message.Shutdown")
}

func init() { proto.RegisterFile("chat-gateway.proto", fileDescriptor_4b278c71b6605e99) }

var fileDescriptor_4b278c71b6605e99 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x9b, 0x6e, 0xe9, 0x9f, 0x33, 0x18, 0x70, 0x98, 0xa8, 0x67, 0x86, 0x40, 0x96, 0x90,
	0xa6, 0x49, 0x24, 0x50, 0x84, 0x98, 0x76, 0xc9, 0x55, 0x2f, 0xe0, 0x26, 0x9d, 0xc4, 0xb5, 0x5b,
	0x4c, 0x16, 0xd1, 0xda, 0xa5, 0x76, 0x3a, 0x71, 0xcb, 0x1b, 0x20, 0xde, 0x80, 0x57, 0xe2, 0x15,
	0x78, 0x10, 0x14, 0xff, 0x49, 0x3a, 0x25, 0x57, 0x89, 0x7d, 0x7e, 0xdf, 0xa7, 0xf3, 0x1d, 0x1f,
	0xc0, 0xe5, 0x0d, 0x37, 0xaf, 0x72, 0x6e, 0xc4, 0x2d, 0xff, 0x91, 0x6c, 0xb6, 0xca, 0x28, 0x1c,
	0xd9, 0xcf, 0x52, 0xad, 0xe8, 0x59, 0xae, 0x54, 0xbe, 0x12, 0x29, 0xdf, 0x14, 0x29, 0x97, 0x52,
	0x19, 0x6e, 0x0a, 0x25, 0xb5, 0xe3, 0xe8, 0x73, 0x5f, 0xb5, 0xa7, 0x45, 0xf9, 0x35, 0x35, 0xc5,
	0x5a, 0x68, 0xc3, 0xd7, 0x1b, 0x07, 0x30, 0x06, 0xf7, 0x3e, 0xaa, 0xbc, 0x90, 0x99, 0xf8, 0x5e,
	0x0a, 0x6d, 0x10, 0xe1, 0x50, 0xf2, 0xb5, 0x20, 0xd1, 0x8b, 0xe8, 0x7c, 0x9c, 0xd9, 0x7f, 0xf6,
	0x12, 0xee, 0x7b, 0x46, 0x6f, 0x94, 0xd4, 0x02, 0x4f, 0x20, 0x36, 0xea, 0x9b, 0x90, 0x9e, 0x72,
	0x07, 0x8f, 0xa9, 0xd2, 0x04, 0xaf, 0x6e, 0xec, 0x21, 0x1c, 0x07, 0xcc, 0xd9, 0xb1, 0x3f, 0x07,
	0x30, 0xfc, 0x24, 0xb4, 0xe6, 0xb9, 0xc0, 0x4b, 0x18, 0xd7, 0x2d, 0x5a, 0xdd, 0xd1, 0x94, 0x26,
	0x2e, 0x44, 0x12, 0x42, 0x24, 0xd7, 0x81, 0xc8, 0x1a, 0x18, 0x53, 0x88, 0x57, 0x55, 0x97, 0xa4,
	0x6f, 0x55, 0x93, 0x24, 0x8c, 0x28, 0xf1, 0xde, 0x89, 0x0d, 0x31, 0xeb, 0x65, 0x8e, 0xc3, 0x29,
	0x0c, 0x56, 0xb6, 0x11, 0x72, 0x60, 0x15, 0xa4, 0x53, 0xa1, 0x4a, 0x33, 0xeb, 0x65, 0x9e, 0xc4,
	0x77, 0x30, 0x5c, 0xbb, 0x1a, 0x39, 0xb4, 0xa2, 0xd3, 0xb6, 0xc8, 0x7f, 0x67, 0xbd, 0x2c, 0xb0,
	0x78, 0x09, 0x23, 0x7d, 0x53, 0x9a, 0x2f, 0xea, 0x56, 0x92, 0xd8, 0x87, 0x6a, 0xe9, 0xe6, 0x9e,
	0x98, 0xf5, 0xb2, 0x9a, 0xa6, 0x4f, 0x21, 0xb6, 0x6d, 0x77, 0x3d, 0x0c, 0x3d, 0x83, 0x81, 0xeb,
	0xb0, 0xb3, 0xfa, 0xbe, 0x99, 0x6a, 0x47, 0x19, 0x49, 0x13, 0xa5, 0x6f, 0xaf, 0xc3, 0x91, 0x02,
	0x8c, 0x42, 0x2f, 0x1f, 0x86, 0x10, 0x8b, 0x9d, 0x90, 0x66, 0xfa, 0xab, 0x0f, 0x47, 0xd5, 0x22,
	0xce, 0xc5, 0x76, 0x57, 0x2c, 0x05, 0xce, 0xfd, 0xb8, 0xf1, 0x49, 0x93, 0x64, 0x7f, 0x93, 0xe8,
	0xa4, 0x75, 0xef, 0x9f, 0xfb, 0xf4, 0xe7, 0xdf, 0x7f, 0xbf, 0xfb, 0x8f, 0xd9, 0x71, 0xba, 0x7b,
	0x93, 0x56, 0x96, 0xa9, 0x35, 0xba, 0x8a, 0x2e, 0xf0, 0x73, 0x78, 0x12, 0xbc, 0xab, 0x6e, 0x96,
	0x8a, 0x92, 0x76, 0xc1, 0xfb, 0x52, 0xeb, 0x7b, 0xc2, 0x1e, 0xec, 0xfb, 0xaa, 0xd2, 0x54, 0xc6,
	0xd7, 0x30, 0xd6, 0xe5, 0x42, 0x2f, 0xb7, 0xc5, 0x42, 0xe0, 0xa3, 0xd6, 0xec, 0x69, 0xfb, 0x8a,
	0x3d, 0xb3, 0x76, 0x13, 0x86, 0xb5, 0x5d, 0xed, 0x70, 0x15, 0x5d, 0x9c, 0x47, 0xaf, 0xa3, 0xc5,
	0xc0, 0x8a, 0xde, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x76, 0x9b, 0xc4, 0xa2, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (ChatService_SubscribeClient, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/protocol.chatService/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/protocol.chatService/logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (ChatService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/protocol.chatService/subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceSubscribeClient{stream}
	return x, nil
}

type ChatService_SubscribeClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *chatServiceSubscribeClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceSubscribeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Subscribe(ChatService_SubscribeServer) error
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedChatServiceServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedChatServiceServer) Subscribe(srv ChatService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.chatService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.chatService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Subscribe(&chatServiceSubscribeServer{stream})
}

type ChatService_SubscribeServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *chatServiceSubscribeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceSubscribeServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.chatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _ChatService_Login_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _ChatService_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribe",
			Handler:       _ChatService_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat-gateway.proto",
}
