// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gopher.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GopherInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GopherInfo) Reset()         { *m = GopherInfo{} }
func (m *GopherInfo) String() string { return proto.CompactTextString(m) }
func (*GopherInfo) ProtoMessage()    {}
func (*GopherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_df81d38ec75a57c2, []int{0}
}

func (m *GopherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GopherInfo.Unmarshal(m, b)
}
func (m *GopherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GopherInfo.Marshal(b, m, deterministic)
}
func (m *GopherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GopherInfo.Merge(m, src)
}
func (m *GopherInfo) XXX_Size() int {
	return xxx_messageInfo_GopherInfo.Size(m)
}
func (m *GopherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GopherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GopherInfo proto.InternalMessageInfo

func (m *GopherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GopherInfo) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GopherInfo) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Login struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_df81d38ec75a57c2, []int{1}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Login) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Login) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Logout struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout) Reset()         { *m = Logout{} }
func (m *Logout) String() string { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()    {}
func (*Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_df81d38ec75a57c2, []int{2}
}

func (m *Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout.Unmarshal(m, b)
}
func (m *Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout.Marshal(b, m, deterministic)
}
func (m *Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout.Merge(m, src)
}
func (m *Logout) XXX_Size() int {
	return xxx_messageInfo_Logout.Size(m)
}
func (m *Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Logout proto.InternalMessageInfo

func (m *Logout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Movement struct {
	// Types that are valid to be assigned to Event:
	//	*Movement_Login
	//	*Movement_Logout
	//	*Movement_Info
	Event                isMovement_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Movement) Reset()         { *m = Movement{} }
func (m *Movement) String() string { return proto.CompactTextString(m) }
func (*Movement) ProtoMessage()    {}
func (*Movement) Descriptor() ([]byte, []int) {
	return fileDescriptor_df81d38ec75a57c2, []int{3}
}

func (m *Movement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movement.Unmarshal(m, b)
}
func (m *Movement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movement.Marshal(b, m, deterministic)
}
func (m *Movement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movement.Merge(m, src)
}
func (m *Movement) XXX_Size() int {
	return xxx_messageInfo_Movement.Size(m)
}
func (m *Movement) XXX_DiscardUnknown() {
	xxx_messageInfo_Movement.DiscardUnknown(m)
}

var xxx_messageInfo_Movement proto.InternalMessageInfo

type isMovement_Event interface {
	isMovement_Event()
}

type Movement_Login struct {
	Login *Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type Movement_Logout struct {
	Logout *Logout `protobuf:"bytes,2,opt,name=logout,proto3,oneof"`
}

type Movement_Info struct {
	Info *GopherInfo `protobuf:"bytes,3,opt,name=info,proto3,oneof"`
}

func (*Movement_Login) isMovement_Event() {}

func (*Movement_Logout) isMovement_Event() {}

func (*Movement_Info) isMovement_Event() {}

func (m *Movement) GetEvent() isMovement_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Movement) GetLogin() *Login {
	if x, ok := m.GetEvent().(*Movement_Login); ok {
		return x.Login
	}
	return nil
}

func (m *Movement) GetLogout() *Logout {
	if x, ok := m.GetEvent().(*Movement_Logout); ok {
		return x.Logout
	}
	return nil
}

func (m *Movement) GetInfo() *GopherInfo {
	if x, ok := m.GetEvent().(*Movement_Info); ok {
		return x.Info
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Movement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Movement_Login)(nil),
		(*Movement_Logout)(nil),
		(*Movement_Info)(nil),
	}
}

func init() {
	proto.RegisterType((*GopherInfo)(nil), "protocol.GopherInfo")
	proto.RegisterType((*Login)(nil), "protocol.Login")
	proto.RegisterType((*Logout)(nil), "protocol.Logout")
	proto.RegisterType((*Movement)(nil), "protocol.Movement")
}

func init() { proto.RegisterFile("gopher.proto", fileDescriptor_df81d38ec75a57c2) }

var fileDescriptor_df81d38ec75a57c2 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x9a, 0xc4, 0x3a, 0xa9, 0x28, 0x83, 0x87, 0x50, 0x3c, 0x94, 0xbd, 0x18, 0x7a,
	0x08, 0x65, 0x15, 0xbc, 0x78, 0xf2, 0x62, 0x84, 0x7a, 0x59, 0x9f, 0x40, 0xcb, 0x36, 0x06, 0x92,
	0x9d, 0x12, 0xb6, 0xa1, 0x7d, 0x0f, 0xdf, 0xc2, 0x97, 0x94, 0x4e, 0x1a, 0x82, 0x1a, 0x0f, 0x9e,
	0x92, 0xd9, 0xff, 0xff, 0xe7, 0xff, 0x18, 0x18, 0xe7, 0xb4, 0x7e, 0x37, 0x75, 0xba, 0xae, 0xc9,
	0x11, 0x8e, 0xf8, 0xb3, 0xa4, 0x52, 0xde, 0x03, 0x3c, 0xb2, 0xf2, 0x64, 0x57, 0x84, 0x08, 0xbe,
	0x7d, 0xad, 0x4c, 0x2c, 0xa6, 0x22, 0x39, 0xd5, 0xfc, 0x8f, 0x63, 0x10, 0xdb, 0xf8, 0x68, 0x2a,
	0x92, 0x40, 0x8b, 0xed, 0x7e, 0xda, 0xc5, 0xc7, 0xed, 0xb4, 0x93, 0x77, 0x10, 0x2c, 0x28, 0x2f,
	0xec, 0xbf, 0x83, 0x57, 0x10, 0x2e, 0x28, 0xa7, 0x8d, 0x1b, 0x4a, 0xca, 0x0f, 0x01, 0xa3, 0x67,
	0x6a, 0x4c, 0x65, 0xac, 0xc3, 0x6b, 0x08, 0xca, 0x7d, 0x07, 0x3b, 0x22, 0x75, 0x9e, 0x76, 0xec,
	0x29, 0x57, 0x67, 0x9e, 0x6e, 0x75, 0x9c, 0x41, 0x58, 0xf2, 0x4e, 0x2e, 0x8d, 0xd4, 0xc5, 0x37,
	0x27, 0x6d, 0x5c, 0xe6, 0xe9, 0x83, 0x03, 0x67, 0xe0, 0x17, 0x76, 0x45, 0x0c, 0x14, 0xa9, 0xcb,
	0xde, 0xd9, 0x1f, 0x23, 0xf3, 0x34, 0x7b, 0x1e, 0x4e, 0x20, 0x30, 0x8d, 0xb1, 0x4e, 0x7d, 0x0a,
	0x38, 0x6b, 0xf5, 0x17, 0x53, 0x37, 0xc5, 0xd2, 0xe0, 0xfc, 0xc0, 0x86, 0x3f, 0xa9, 0x26, 0x83,
	0x2b, 0xa5, 0x87, 0xaa, 0x83, 0xc4, 0x5f, 0x78, 0x7f, 0x66, 0x6e, 0xc1, 0xaf, 0xa8, 0x31, 0x88,
	0xbd, 0xde, 0x5d, 0x67, 0x32, 0xf0, 0x26, 0xbd, 0x44, 0xcc, 0xc5, 0x5b, 0xc8, 0xc2, 0xcd, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0xaf, 0x4e, 0x6f, 0xfa, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GopherServiceClient is the client API for GopherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GopherServiceClient interface {
	Login(ctx context.Context, in *Login, opts ...grpc.CallOption) (*GopherInfo, error)
	Logout(ctx context.Context, in *Logout, opts ...grpc.CallOption) (*GopherInfo, error)
	Move(ctx context.Context, opts ...grpc.CallOption) (GopherService_MoveClient, error)
}

type gopherServiceClient struct {
	cc *grpc.ClientConn
}

func NewGopherServiceClient(cc *grpc.ClientConn) GopherServiceClient {
	return &gopherServiceClient{cc}
}

func (c *gopherServiceClient) Login(ctx context.Context, in *Login, opts ...grpc.CallOption) (*GopherInfo, error) {
	out := new(GopherInfo)
	err := c.cc.Invoke(ctx, "/protocol.GopherService/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherServiceClient) Logout(ctx context.Context, in *Logout, opts ...grpc.CallOption) (*GopherInfo, error) {
	out := new(GopherInfo)
	err := c.cc.Invoke(ctx, "/protocol.GopherService/logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gopherServiceClient) Move(ctx context.Context, opts ...grpc.CallOption) (GopherService_MoveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GopherService_serviceDesc.Streams[0], "/protocol.GopherService/move", opts...)
	if err != nil {
		return nil, err
	}
	x := &gopherServiceMoveClient{stream}
	return x, nil
}

type GopherService_MoveClient interface {
	Send(*Movement) error
	Recv() (*Movement, error)
	grpc.ClientStream
}

type gopherServiceMoveClient struct {
	grpc.ClientStream
}

func (x *gopherServiceMoveClient) Send(m *Movement) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gopherServiceMoveClient) Recv() (*Movement, error) {
	m := new(Movement)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GopherServiceServer is the server API for GopherService service.
type GopherServiceServer interface {
	Login(context.Context, *Login) (*GopherInfo, error)
	Logout(context.Context, *Logout) (*GopherInfo, error)
	Move(GopherService_MoveServer) error
}

// UnimplementedGopherServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGopherServiceServer struct {
}

func (*UnimplementedGopherServiceServer) Login(ctx context.Context, req *Login) (*GopherInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedGopherServiceServer) Logout(ctx context.Context, req *Logout) (*GopherInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedGopherServiceServer) Move(srv GopherService_MoveServer) error {
	return status.Errorf(codes.Unimplemented, "method Move not implemented")
}

func RegisterGopherServiceServer(s *grpc.Server, srv GopherServiceServer) {
	s.RegisterService(&_GopherService_serviceDesc, srv)
}

func _GopherService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Login)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GopherService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherServiceServer).Login(ctx, req.(*Login))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Logout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GopherServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GopherService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GopherServiceServer).Logout(ctx, req.(*Logout))
	}
	return interceptor(ctx, in, info, handler)
}

func _GopherService_Move_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GopherServiceServer).Move(&gopherServiceMoveServer{stream})
}

type GopherService_MoveServer interface {
	Send(*Movement) error
	Recv() (*Movement, error)
	grpc.ServerStream
}

type gopherServiceMoveServer struct {
	grpc.ServerStream
}

func (x *gopherServiceMoveServer) Send(m *Movement) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gopherServiceMoveServer) Recv() (*Movement, error) {
	m := new(Movement)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GopherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.GopherService",
	HandlerType: (*GopherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "login",
			Handler:    _GopherService_Login_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _GopherService_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "move",
			Handler:       _GopherService_Move_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gopher.proto",
}
