// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gopher.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protocol {
  public static partial class GopherService
  {
    static readonly string __ServiceName = "protocol.GopherService";

    static readonly grpc::Marshaller<global::Protocol.Login> __Marshaller_protocol_Login = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.Login.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protocol.GopherInfo> __Marshaller_protocol_GopherInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.GopherInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protocol.Logout> __Marshaller_protocol_Logout = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.Logout.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protocol.Movement> __Marshaller_protocol_Movement = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.Movement.Parser.ParseFrom);

    static readonly grpc::Method<global::Protocol.Login, global::Protocol.GopherInfo> __Method_login = new grpc::Method<global::Protocol.Login, global::Protocol.GopherInfo>(
        grpc::MethodType.Unary,
        __ServiceName,
        "login",
        __Marshaller_protocol_Login,
        __Marshaller_protocol_GopherInfo);

    static readonly grpc::Method<global::Protocol.Logout, global::Protocol.GopherInfo> __Method_logout = new grpc::Method<global::Protocol.Logout, global::Protocol.GopherInfo>(
        grpc::MethodType.Unary,
        __ServiceName,
        "logout",
        __Marshaller_protocol_Logout,
        __Marshaller_protocol_GopherInfo);

    static readonly grpc::Method<global::Protocol.Movement, global::Protocol.Movement> __Method_move = new grpc::Method<global::Protocol.Movement, global::Protocol.Movement>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "move",
        __Marshaller_protocol_Movement,
        __Marshaller_protocol_Movement);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protocol.GopherReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GopherService</summary>
    public abstract partial class GopherServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protocol.GopherInfo> login(global::Protocol.Login request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Protocol.GopherInfo> logout(global::Protocol.Logout request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task move(grpc::IAsyncStreamReader<global::Protocol.Movement> requestStream, grpc::IServerStreamWriter<global::Protocol.Movement> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GopherService</summary>
    public partial class GopherServiceClient : grpc::ClientBase<GopherServiceClient>
    {
      /// <summary>Creates a new client for GopherService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GopherServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GopherService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GopherServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GopherServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GopherServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protocol.GopherInfo login(global::Protocol.Login request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protocol.GopherInfo login(global::Protocol.Login request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.GopherInfo> loginAsync(global::Protocol.Login request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return loginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.GopherInfo> loginAsync(global::Protocol.Login request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_login, null, options, request);
      }
      public virtual global::Protocol.GopherInfo logout(global::Protocol.Logout request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return logout(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protocol.GopherInfo logout(global::Protocol.Logout request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_logout, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.GopherInfo> logoutAsync(global::Protocol.Logout request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return logoutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.GopherInfo> logoutAsync(global::Protocol.Logout request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_logout, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Protocol.Movement, global::Protocol.Movement> move(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return move(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Protocol.Movement, global::Protocol.Movement> move(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_move, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GopherServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GopherServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GopherServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_login, serviceImpl.login)
          .AddMethod(__Method_logout, serviceImpl.logout)
          .AddMethod(__Method_move, serviceImpl.move).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GopherServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protocol.Login, global::Protocol.GopherInfo>(serviceImpl.login));
      serviceBinder.AddMethod(__Method_logout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protocol.Logout, global::Protocol.GopherInfo>(serviceImpl.logout));
      serviceBinder.AddMethod(__Method_move, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Protocol.Movement, global::Protocol.Movement>(serviceImpl.move));
    }

  }
}
#endregion
